### ISSUE TITLE
Add functionality

### ISSUE THREAD

**Issue by zxcCEn** [mxy493/YOLOv5-Qt#3]
Hello, I want to add two more setting modules. The mode switch has been achieved. Is it feasible

**Comment by mxy493** [comment]
> Hello, I want to add two more setting modules. The mode switch has been achieved. Is it feasible

what settings do you want to add?

**Comment by zxcCEn** [comment]
就是您的程序需是通过点击setting这个按钮来调整阈值这些参数，我想再添加两个setting这个模块，并实现里面的功能。就是再复制两个setting。十分感谢

**Comment by mxy493** [comment]
@zxcCEn  你是说你在改代码吗？如果是的话你的问题需要再具体一些，也许我可以提供一些想法给你参考

**Comment by zxcCEn** [comment]
十分感谢您，我解决了
